### PR TITLE
WIP: process the coffee-script ast using a custom walker

### PR DESCRIPTION
**Pull request by addisonj**
Hi Phil,

I need to do some analysis of coffee-script and so I decided to take this is a starting point.

I followed escomplex-ast-moz and escomplex-js as a template and have this mostly working with using the AST that `coffee-script` generates (instead of `coffee-script-redux` which seems to be not as active these days).

The tests currently pass and if you run `coffee src/index.coffee` you will get some output and manually checking against the code it seems close to what it should be.

I wasn't completely sure of the traits though and wanted another set of eyes to make sure I am properly counting all the different language constructs.

There is a bit of clean up before merging this as well as verifying that it works as expected, but wanted to get some collaboration on it.

### CODE REVIEW

**Comment by philbooth** [comment]
This looks awesome!

I really lapsed on the CS front so it is great to see someone pick it up and run with it. Sorry about having to figure out that traits stuff. I've never been entirely happy with where I got to on that front and they aren't documented at all so I appreciate it takes a bit of figuring out.

Anyway, I could merge this. Or I could delete my repo entirely and have escomplex etc just link to yours. Which would you prefer?

My thinking runs thus: I have done basically no work on the CS walker and am not actively using CS for any projects right now. You have basically done all the work on the CS walker and are actively using CS right now. So things will probably be a lot simpler for both of us if I get out of the way and you can sidestep having to open pull requests against somebody else's repo. What do you reckon?

Either way, thanks for doing this, I think it is excellent. :)

**Comment by philbooth** [comment]
Re: checking the traits and ensuring you have covered all bases, I think the only way to do this properly is by writing a buttload of tests throwing more and more source code at it. It's kind of repetitive and boring work, but it can be done gradually. And obviously the bonus is that you get a comprehensive test suite as a result, which pays dividends in the future.

**Comment by addisonj** [comment]
@philbooth if you wanted to make me a collaborator on the project and add me to the npm authors list, that would work for me.

I don't see too much of a problem working from here and you already have the npm name and repo.

As far as testing things, that is what I figured, but if you have insight into what counts as a line of code and how to calculate halstead by hand, that might be helpful.

**Comment by philbooth** [comment]
Well the npm name can be transferred too, no worries.

Anyway, in the meantime I've added you as a contributor/owner on GitHub/npm across all the projects. If you change your mind about ownership of this module/package at any point, just shout. :)

**Comment by addisonj** [comment]
Appreciate it!

I will certainly take more ownership over this project and will see what I can do with the others.

**Pull request merged**
